
import csv
import re

def parse_csv_to_typescript(student_file, schedule_file, output_file):
    day_map = {
        'SAT': '토요일',
        'TUE': '화요일',
        'WED': '수요일',
        'THU': '목요일',
        'FRI': '금요일',
    }

    # 1. Parse Students
    students_by_class = {}
    with open(student_file, 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        next(reader)  # Skip header
        for row in reader:
            if len(row) > 17:
                student_name = row[9].strip()
                course_name = row[16].strip()
                if not course_name: continue
                
                # Create a more general key, as day is in the schedule
                if course_name not in students_by_class:
                    students_by_class[course_name] = []
                if student_name not in students_by_class[course_name]:
                    students_by_class[course_name].append(student_name)

    # 2. Parse Schedule
    schedule_data = []
    with open(schedule_file, 'r', encoding='utf-8') as f:
        lines = list(csv.reader(f))

    day_indices = [i for i, row in enumerate(lines) if row and row[0] in day_map]

    for i, start_index in enumerate(day_indices):
        day_abbr = lines[start_index][0]
        day_full = day_map.get(day_abbr)
        if not day_full: continue

        end_index = day_indices[i+1] if i + 1 < len(day_indices) else len(lines)
        day_lines = lines[start_index:end_index]
        
        # Robustly find classroom headers for the current day block
        classroom_headers = []
        # Find the row that looks like a header (contains '1', '2', etc.)
        for row in day_lines:
            if any(val.strip() == '1' for val in row) and any(val.strip() == '2' for val in row):
                classroom_headers = [h.strip() for h in row]
                break
        
        if not classroom_headers: continue

        for row_idx, row in enumerate(day_lines):
            if not row or not row[0] or '~' not in row[0]:
                continue

            time_str = row[0].strip()
            time_parts = [t.strip() for t in time_str.split('~')]
            if len(time_parts) != 2: continue
            
            start_time, end_time = time_parts[0], time_parts[1]

            class_row = row
            instructor_row_idx = row_idx + 2
            instructor_row = day_lines[instructor_row_idx] if instructor_row_idx < len(day_lines) else []

            for col_idx, class_name_raw in enumerate(class_row):
                class_name = class_name_raw.strip()
                if not class_name or col_idx == 0 or col_idx >= len(classroom_headers):
                    continue

                classroom = classroom_headers[col_idx]
                if not classroom: continue

                teacher = instructor_row[col_idx].strip() if col_idx < len(instructor_row) and instructor_row[col_idx] else '미정'
                
                enrolled_students = students_by_class.get(class_name, [])

                schedule_data.append({
                    "day_of_week": day_full,
                    "classroom": f"강의실 {classroom}",
                    "start_time": start_time,
                    "end_time": end_time,
                    "subject_name": class_name,
                    "teacher_name": teacher,
                    "students": enrolled_students,
                    "capacity": 8,
                    "current_students": len(enrolled_students)
                })

    # 3. Write to TypeScript file
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('// This file is auto-generated from CSV data\n')
        f.write('// Do not edit this file manually\n\n')
        f.write('import { Class } from "@/types";\n\n')
        f.write('export const SCHEDULE_DATA: Class[] = [\n')
        for item in schedule_data:
            f.write('  {\n')
            f.write(f'    day_of_week: "{item["day_of_week"]}",\n')
            f.write(f'    classroom: "{item["classroom"]}",\n')
            f.write(f'    start_time: "{item["start_time"]}",\n')
            f.write(f'    end_time: "{item["end_time"]}",\n')
            f.write(f'    subject_name: "{item["subject_name"]}",\n')
            f.write(f'    teacher_name: "{item["teacher_name"]}",\n')
            students_str = ", ".join([f'"{s}"' for s in item["students"]])
            f.write(f'    students: [{students_str}],\n')
            f.write(f'    capacity: {item["capacity"]},\n')
            f.write(f'    current_students: {item["current_students"]}\n')
            f.write('  },\n')
        f.write('];\n')

if __name__ == "__main__":
    try:
        student_csv = 'data/학생데이터.csv'
        schedule_csv = 'data/시간표.csv'
        ts_output = 'lib/scheduleData.ts'
        parse_csv_to_typescript(student_csv, schedule_csv, ts_output)
        print(f"✅ Successfully generated '{ts_output}'")
    except FileNotFoundError as e:
        print(f"❌ Error: Could not find file. Please check the path: {e}")
    except Exception as e:
        print(f"❌ An unexpected error occurred: {e}")
