# Generated by Django 4.2.11 on 2025-06-03 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('master_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('name_parent', models.TextField(blank=True, max_length=10, null=True)),
                ('phone_parent', models.TextField(blank=True, max_length=30)),
                ('phone_user', models.TextField(blank=True, max_length=10, null=True)),
                ('gender', models.TextField(blank=True, max_length=5, null=True)),
                ('school', models.TextField(blank=True, max_length=30, null=True)),
                ('grade', models.TextField(blank=True, max_length=10, null=True)),
                ('input_path', models.TextField(blank=True, max_length=20, null=True)),
                ('status', models.TextField(blank=True, max_length=20, null=True)),
                ('counsel', models.TextField(blank=True, max_length=1000, null=True)),
                ('memo', models.TextField(blank=True, max_length=1000, null=True)),
                ('birth', models.TextField(blank=True, max_length=30, null=True)),
                ('regdate', models.TextField(blank=True, max_length=30, null=True)),
                ('opt_out', models.TextField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_date', models.TextField(blank=True, max_length=30, null=True)),
                ('memo', models.TextField(blank=True, max_length=1000, null=True)),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE,
                                             related_name='histories', to='api.studentmaster')),
            ],
        ),
        migrations.CreateModel(
            name='CourseMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('term', models.TextField(blank=True, max_length=20, null=True)),
                ('course', models.TextField(blank=True, max_length=20)),
                ('phone_parent', models.TextField(blank=True, max_length=30)),
                ('subject', models.TextField(blank=True, max_length=20, null=True)),
                ('time', models.TextField(blank=True, max_length=30, null=True)),
                ('openlab', models.TextField(blank=True, max_length=30, null=True)),
                ('pay', models.TextField(blank=True, max_length=10, null=True)),
                ('memo', models.TextField(blank=True, max_length=1000, null=True)),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE,
                                             related_name='courses', to='api.studentmaster')),
            ],
        ),
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('term', models.TextField(blank=True, max_length=20, null=True)),
                ('subject', models.TextField(blank=True, max_length=20, null=True)),
                ('round', models.TextField(blank=True, max_length=20, null=True)),
                ('status', models.TextField(blank=True, max_length=20, null=True)),
                ('res_date', models.TextField(blank=True, max_length=30, null=True)),
                ('memo', models.TextField(blank=True, max_length=1000, null=True)),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE,
                                             related_name='attends', to='api.studentmaster')),
            ],
        ),
    ]
