# Generated by Django 4.2.11 on 2025-06-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_slacklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackLogNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.CharField(max_length=30, unique=True)),
                ('posted_dt', models.DateTimeField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='SlackLog',
        ),
    ]
