# Generated by Django 4.2.11 on 2025-06-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_slacklognew_delete_slacklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmaster',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
