# Generated by Django 4.2.11 on 2025-07-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0005_alter_studentmaster_imgfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmaster',
            name='imgfile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
