# Generated by Django 4.2.11 on 2025-07-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_alter_studentmaster_imgfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_semester', models.CharField(max_length=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
