# Generated by Django 4.2.11 on 2025-07-05 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_semesterstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('topic', models.CharField(max_length=100)),
                ('course_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks',
                                                  to='api.coursemain')),
            ],
            options={
                'ordering': ['week'],
                'unique_together': {('course_main', 'week')},
            },
        ),
    ]
