# Generated by Django 4.2.11 on 2025-07-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0008_coursemain_courseweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announce_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='공지 ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('date', models.DateField(verbose_name='등록일')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항 목록',
                'db_table': 'announcement',
                'ordering': ['-date'],
            },
        ),
    ]
