# Generated by Django 4.2.11 on 2025-07-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0009_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='announce_id',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
