# Generated by Django 4.2.11 on 2025-07-17 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0010_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedNextCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=6)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentmaster')),
            ],
            options={
                'unique_together': {('student', 'term')},
            },
        ),
    ]
