# Generated by Django 4.2.11 on 2025-07-19 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0011_recommendednextcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendednextcourse',
            name='updated_at',
        ),
    ]
