# Generated by Django 4.2.11 on 2025-08-31 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0013_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('자격증', '자격증'), ('대회', '대회')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('term', models.CharField(max_length=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentmaster')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
