# Generated by Django 4.2.11 on 2025-09-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0015_teacherfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherfeedback',
            name='week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
