# Generated by Django 4.2.11 on 2025-09-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0016_teacherfeedback_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherfeedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='teacherfeedback',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='teacherfeedback',
            name='teacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
