# Generated by Django 4.2.11 on 2026-03-07 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_teacherfeedback_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=20, unique=True)),
                ('subject_name', models.CharField(max_length=100)),
                ('day_of_week', models.CharField(choices=[('Monday', '월요일'), ('Tuesday', '화요일'), ('Wednesday', '수요일'), ('Thursday', '목요일'), ('Friday', '금요일'), ('Saturday', '토요일'), ('Sunday', '일요일')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('classroom', models.CharField(blank=True, max_length=50, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('Kiosk', '키오스크'), ('Manual', '수동')], default='Kiosk', max_length=10)),
                ('notification_sent', models.BooleanField(default=False)),
                ('course_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='api.courseclass')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='api.studentmaster')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='api.courseclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.studentmaster')),
            ],
            options={
                'unique_together': {('student', 'course_class')},
            },
        ),
    ]
