# Generated by Django 4.2.11 on 2026-03-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_courseclass_attendancelog_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclass',
            name='class_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
