# Generated by Django 4.2.11 on 2026-03-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_academicsemester'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterstatus',
            name='new_count',
            field=models.IntegerField(default=0),
        ),
    ]
