# Generated by Django 4.2.11 on 2026-03-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_semesterstatus_new_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='status',
            field=models.CharField(choices=[('present', '출석'), ('absent', '결석')], default='present', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='check_in_time',
            field=models.DateTimeField(),
        ),
    ]
