# Generated by Django 4.2.11 on 2026-03-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_messagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterstatus',
            name='call_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
