# Generated by Django 4.2.11 on 2026-03-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_announcement_edit_url_announcement_link_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterstatus',
            name='total_revenue',
            field=models.BigIntegerField(default=0),
        ),
    ]
