# Generated by Django 4.2.11 on 2026-03-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_semesterstatus_total_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterstatus',
            name='unpaid_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
