# Generated by Django 4.2.11 on 2026-03-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_semesterstatus_unpaid_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('short', '단기업무'), ('mid', '중기업무'), ('feedback', '학생피드백')], max_length=20)),
                ('content', models.CharField(max_length=500)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
