# Generated by Django 4.2.11 on 2026-04-03 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_messagetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=6)),
                ('tier', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='api.studentmaster')),
            ],
            options={
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
