# Generated by Django 4.2.11 on 2026-04-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_studenttier'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttier',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studenttier',
            name='tier',
            field=models.CharField(default='Bronze', max_length=20),
        ),
    ]
